### PR TITLE
[otap-df-otap] Add error handling for arrow records build in Syslog CEF Receiver

### LINKED ISSUE #2182: Syslog CEF receiver can panic if there is an error constructing OTAP record batches
For example, from invalid UTF-8 sequences:
```
thread 'pipeline-perftest1-main-core-3' (238483) panicked at crates/otap/src/syslog_cef_receiver.rs:454:115:
Failed to build Arrow records: ArrowError(InvalidArgumentError("Encountered non UTF-8 data: invalid utf-8 sequence of 1 bytes from index 4"))
```

### PR DESCRIPTION
**Pull request by utpilla**
# Change Summary

@cijothomas reported intermittent errors logs saying that arrow records build within Syslog CEF receiver failed with the following error:
```
thread 'pipeline-perftest1-main-core-3' (238483) panicked at crates/otap/src/syslog_cef_receiver.rs:454:115:
Failed to build Arrow records: ArrowError(InvalidArgumentError("Encountered non UTF-8 data: invalid utf-8 sequence of 1 bytes from index 4"))
```

The PR adds error handling for building Arrow records.

## What issue does this PR close?

Closes #2182

### CODE REVIEW

File: rust/otap-dataflow/crates/otap/src/syslog_cef_receiver.rs
Comment (utpilla) [inline rust/otap-dataflow/crates/otap/src/syslog_cef_receiver.rs:1]: Note to reviewers: Please use the "Hide Whitespace" option for easier review.

File: rust/otap-dataflow/crates/otap/src/syslog_cef_receiver.rs [hunk 1]
```diff
@@ -400,14 +400,21 @@ impl local::Receiver<OtapPdata> for SyslogCefReceiver {
...
+                                                                OtapPdata::new_todo_context(arrow_records.into())
+                                                            );
+                                                            let mut m = metrics.borrow_mut();
+                                                            match &res {
+                                                                Ok(_) => m.received_logs_forwarded.add(items),
+                                                                Err(_) => m.received_logs_forward_failed.add(items),
+                                                            }
+                                                        }
+                                                        Err(e) => {
+                                                            otel_warn!("syslog_cef_receiver.arrow_records.build_failed", error = %e, message = "Failed to build Arrow records, dropping batch");
```
Comment (cijothomas) [inline rust/otap-dataflow/crates/otap/src/syslog_cef_receiver.rs:415]: could the raw payload be debug logged too?

File: rust/otap-dataflow/crates/otap/src/syslog_cef_receiver.rs [hunk 2]
```diff
@@ -400,14 +400,21 @@ impl local::Receiver<OtapPdata> for SyslogCefReceiver {
...
+                                                            metrics.borrow_mut().received_logs_forward_failed.add(items);
+                                                        }
```
Comment (cijothomas) [inline rust/otap-dataflow/crates/otap/src/syslog_cef_receiver.rs:417]: metrics looks good to me! The WARN might be too noisy since it'll print on each failed log.

File: rust/otap-dataflow/crates/otap/src/syslog_cef_receiver.rs (hunk 1 above)
Comment (utpilla) [reply rust/otap-dataflow/crates/otap/src/syslog_cef_receiver.rs:415]: The problem is that error type doesn't have any information about which entry in the batch caused the failure. All we know is batch couldn't be built into `OtapArrowRecords` and the reason it failed but not the problematic entry.

File: rust/otap-dataflow/crates/otap/src/syslog_cef_receiver.rs (hunk 2 above)
Comment (utpilla) [reply rust/otap-dataflow/crates/otap/src/syslog_cef_receiver.rs:417]: I also created #2181 to fix the handling of invalid UTF-8 str values. With the fix in #2181, it should be uncommon for arrow records build to fail.

So, using `otel_warn` should be okay now. In fact, it would help point out any weird issue if at all it comes up.
