### PR TITLE
Fix flakey validation tests and improve runtime

### LINKED ISSUE #2184: Flaky CI test
PASS [   0.014s] (2394/2397) otap-df-validation validation_types::tests::signal_drop_with_ratio_bounds
        FAIL [  26.128s] (2395/2397) otap-df-validation tests::no_processor
  stdout ───

    running 1 test
    2026-03-04T05:25:26.063Z  INFO  otap-df-admin::endpoint.start: Admin HTTP server listening [bind_address=127.0.0.1:17055]
    2026-03-04T05:25:26.066Z  INFO  otap-df-otap::otlp.exporter.grpc.start: [grpc_endpoint=http://127.0.0.1:19601] entity/node.attrs: node.id=exporter node.urn=urn:otel:exporter:otlp node.type=exporter pipeline.id=suv pipeline.group.id=validation_test core.id=0 numa.node.id=0 process.instance.id=AGOLOTXBVV3ABNIL6ZUUAUBTDU host.id=runnervmnay03 container.id=
    2026-03-04T05:25:26.066Z  INFO  otap-df-otap::otlp.receiver.grpc.start: Starting OTLP gRPC receiver [endpoint=127.0.0.1:15056] entity/node.attrs: node.id=receiver node.urn=urn:otel:receiver:otlp node.type=receiver pipeline.id=suv pipeline.group.id=validation_test core.id=0 numa.node.id=0 process.instance.id=AGOLOTXBVV3ABNIL6ZUUAUBTDU host.id=runnervmnay03 container.id=
    2026-03-04T05:25:26.070Z  INFO  otap-df-otap::otlp.receiver.grpc.start: Starting OTLP gRPC receiver [endpoint=127.0.0.1:23731] entity/node.attrs: node.id=control_receiver1 node.urn=urn:otel:receiver:otlp node.type=receiver pipeline.id=validate pipeline.group.id=validation_test core.id=2 numa.node.id=0 process.instance.id=AGOLOTXBVV3ABNIL6ZUUAUBTDU host.id=runnervmnay03 container.id=
    2026-03-04T05:25:26.071Z  INFO  otap-df-otap::otlp.receiver.grpc.start: Starting OTLP gRPC receiver [endpoint=127.0.0.1:19601] entity/node.attrs: node.id=suv_receiver node.urn=urn:otel:receiver:otlp node.type=receiver pipeline.id=validate pipeline.group.id=validation_test core.id=2 numa.node.id=0 process.instance.id=AGOLOTXBVV3ABNIL6ZUUAUBTDU host.id=runnervmnay03 container.id=
    2026-03-04T05:25:26.071Z  INFO  otap-df-otap::otlp.exporter.grpc.start: [grpc_endpoint=http://127.0.0.1:15056] entity/node.attrs: node.id=suv_exporter node.urn=urn:otel:exporter:otlp node.type=exporter pipeline.id=traffic_gen pipeline.group.id=validation_test core.id=1 numa.node.id=0 process.instance.id=AGOLOTXBVV3ABNIL6ZUUAUBTDU host.id=runnervmnay03 container.id=
    2026-03-04T05:25:26.071Z  INFO  otap-df-otap::otlp.exporter.grpc.start: [grpc_endpoint=http://127.0.0.1:23731] entity/node.attrs: node.id=control_exporter1 node.urn=urn:otel:exporter:otlp node.type=exporter pipeline.id=traffic_gen pipeline.group.id=validation_test core.id=1 numa.node.id=0 process.instance.id=AGOLOTXBVV3ABNIL6ZUUAUBTDU host.id=runnervmnay03 container.id=
    2026-03-04T05:25:26.071Z  INFO  otap-df-otap::fake_data_generator.start: Fake data generator receiver started [signals_per_second=100 signals/sec, max_batch_size=100, metrics_per_iteration=0, traces_per_iteration=0, logs_per_iteration=100, data_source=Static, generation_strategy=Fresh] entity/node.attrs: node.id=traffic_gen node.urn=urn:otel:receiver:traffic_generator node.type=receiver pipeline.id=traffic_gen pipeline.group.id=validation_test core.id=1 numa.node.id=0 process.instance.id=AGOLOTXBVV3ABNIL6ZUUAUBTDU host.id=runnervmnay03 container.id=
    2026-03-04T05:25:52.163Z  INFO  otap-df-admin::shutdown.requested: [wait=true, timeout_secs=60]
    2026-03-04T05:25:52.163Z  INFO  otap-df-admin::shutdown.failed: [error_count=1]
    2026-03-04T05:25:52.163Z  INFO  otap-df-state::state.observed_event: [observed_event=EngineEvent { key: DeployedPipelineKey { pipeline_group_id: "validation_test", pipeline_id: "traffic_gen", core_id: 1 }, node_id: None, node_kind: None, time: SystemTime { tv_sec: 1772601952, tv_nsec: 163701254 }, type: Request(ShutdownRequested), message: Some("Shutdown requested via the `/pipeline-groups/shutdown` endpoint.") }]
    2026-03-04T05:25:52.163Z  INFO  otap-df-otap::fake_data_generator.shutdown: 
    2026-03-04T05:25:52.163Z  INFO  otap-df-state::state.observed_event: [observed_event=EngineEvent { key: DeployedPipelineKey { pipeline_group_id: "validation_test", pipeline_id: "suv", core_id: 0 }, node_id: None, node_kind: None, time: SystemTime { tv_sec: 1772601952, tv_nsec: 163833817 }, type: Request(ShutdownRequested), message: Some("Shutdown requested via the `/pipeline-groups/shutdown` endpoint.") }]
    2026-03-04T05:25:52.163Z  INFO  otap-df-otap::otlp.receiver.shutdown: 
    2026-03-04T05:25:52.164Z  INFO  otap-df-otap::otlp.exporter.grpc.shutdown:  entity/node.attrs: node.id=control_exporter1 node.urn=urn:otel:exporter:otlp node.type=exporter pipeline.id=traffic_gen pipeline.group.id=validation_test core.id=1 numa.node.id=0 process.instance.id=AGOLOTXBVV3ABNIL6ZUUAUBTDU host.id=runnervmnay03 container.id=
    2026-03-04T05:25:52.164Z  INFO  otap-df-otap::otlp.exporter.grpc.shutdown:  entity/node.attrs: node.id=suv_exporter node.urn=urn:otel:exporter:otlp node.type=exporter pipeline.id=traffic_gen pipeline.group.id=validation_test core.id=1 numa.node.id=0 process.instance.id=AGOLOTXBVV3ABNIL6ZUUAUBTDU host.id=runnervmnay03 container.id=
    2026-03-04T05:25:52.165Z  INFO  otap-df-otap::otlp.exporter.grpc.shutdown:  entity/node.attrs: node.id=exporter node.urn=urn:otel:exporter:otlp node.type=exporter pipeline.id=suv pipeline.group.id=validation_test core.id=0 numa.node.id=0 process.instance.id=AGOLOTXBVV3ABNIL6ZUUAUBTDU host.id=runnervmnay03 container.id=
    test tests::no_processor ... FAILED

    failures:

    failures:
        tests::no_processor

    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 38 filtered out; finished in 26.11s
    
  stderr ───

    thread 'pipeline-validation_test-validate-core-2' (34054) panicked at crates/pdata/src/testing/equiv/mod.rs:77:36:
    at least one input
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

    thread 'tests::no_processor' (34042) panicked at crates/validation/src/lib.rs:63:14:
    validation scenario failed: Http("HTTP status server error (500 Internal Server Error) for url (http://127.0.0.1:17055/pipeline-groups/shutdown?wait=true)")

  Cancelling due to test failure: 2 tests still running
        SLOW [> 60.000s] (─────────) otap-df-validation tls_tests::mtls_no_processor
        SLOW [> 60.000s] (─────────) otap-df-validation tls_tests::tls_no_processor
        PASS [  85.240s] (2396/2397) otap-df-validation tls_tests::mtls_no_processor
        PASS [  85.153s] (2397/2397) otap-df-validation tls_tests::tls_no_processor
────────────
     Summary [ 219.013s] 2397 tests run: 2396 passed (6 slow), 1 failed, 3 skipped
        FAIL [  26.128s] (2395/2397) otap-df-validation tests::no_processor
error: test run failed
error: process didn't exit successfully: `/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo nextest run --manifest-path /home/runner/work/otel-arrow/otel-arrow/rust/otap-dataflow/Cargo.toml --target-dir /home/runner/work/otel-arrow/otel-arrow/rust/otap-dataflow/target/llvm-cov-target --all-features --workspace` (exit status: 100)
Error: Process completed with exit code 100.

### PR DESCRIPTION
**Pull request by c1ly**
# Change Summary

Fix validation tests, added a message received timeout in the validation exporter that will trigger the validation checks and report a finished signal via the telemetry metrics, only runs the validation checks once vs every message received.

## What issue does this PR close?

* Closes #2184 and #2227

## How are these changes tested?

Added unit tests and confirmed that validation tests consistently pass in cicd

## Are there any user-facing changes?

yes, changed expected_within() parameter type from duration to u64

### CODE REVIEW

File: rust/otap-dataflow/crates/validation/src/validation_exporter.rs [hunk 1]
```diff
@@ -156,17 +177,30 @@ impl Exporter<OtapPdata> for ValidationExporter {
...
             match msg_chan.recv().await? {
                 Message::Control(NodeControlMsg::CollectTelemetry {
                     mut metrics_reporter,
                 }) => {
+                    // Check idle timeout: if enough time has passed since the
+                    // last message and we have received at least one SUV
+                    // message, perform the final validation and signal
+                    // finished.
+                    if last_message_time.elapsed() >= self.idle_timeout
+                        && self.metrics.finished.get() != 1
```
Comment (jmacd) [inline rust/otap-dataflow/crates/validation/src/validation_exporter.rs:191]:
```suggestion
                        && self.metrics.finished.get() != 1
                        && !self.suv_msgs.is_empty()
```

Comment (c1ly) [reply rust/otap-dataflow/crates/validation/src/validation_exporter.rs:191]: fixed
