### PR TITLE
Batch processor: Nack when inbound or outbound slots are full

### LINKED ISSUE #2194: Batch processor returns fatal error on inbound slot exhaustion and crashes engine
When the batch processor's inbound slots are fully occupied (default limit: 1024), the next subscribed message causes a fatal `ProcessorError("inbound slots not available")` that crashes the entire pipeline.

I think BatchProcessor should just `Nack` the request instead of returning Err.
Also, another question - if a processor returns Err, is it expected that engine crashes?

Repro: Run engine with this config:

```yaml
# Repro: batch processor crashes when inbound slots are exhausted.
# The retry processor subscribes (ACKS|NACKS) on every message, so
# has_subscribers()=true at the batch processor. With a long flush
# timeout the default 1024 inbound slots exhaust in ~2s, hitting a
# fatal ProcessorError("inbound slots not available") that kills the
# pipeline.

version: otel_dataflow/v1
engine: {}
groups:
  default:
    pipelines:
      main:
        policies:
          channel_capacity:
            control:
              node: 100
              pipeline: 100
            pdata: 128
          resources:
            core_allocation:
              type: core_count
              count: 1

        nodes:
          receiver:
            type: receiver:traffic_generator
            config:
              traffic_config:
                max_batch_size: 1
                signals_per_second: 5000
                log_weight: 100
              registry_path: https://github.com/open-telemetry/semantic-conventions.git[model]
          retry:
            type: processor:retry
            config: {}

          batch:
            type: processor:batch
            config:
              otap:
                min_size: 100000
                sizer: items
              flush_timeout: 10s

          noop:
            type: exporter:noop
            config:

        connections:
          - from: receiver
            to: retry
          - from: retry
            to: batch
          - from: batch
            to: noop
```

### PR DESCRIPTION
**Pull request by jmacd**
# Change Summary

Fixes engine-level error when the batch_processor inbound/outbound slots are full.

For inbound failures: Nack the message and do not admit.
For outbound failures: Nack the message but let the request fly.

Adds two new metrics for these cases.

Adds a simpler SlotMap allocator: allocate_with_data() makes the two callsites in batch_processor easier to read.

Adds several notes and TODOs:

- It is easy for callers to mistakenly invoke route_ack() and route_nack(), but it breaks instrumentation b/c the timing measurement is not captured.
- Failure to Ack/Nack are engine-level errors; we should have something consistent for dealing with lost Ack/Nack messages.

## What issue does this PR close?

Fixes #2194

### CODE REVIEW

File: rust/otap-dataflow/crates/core-nodes/src/processors/batch_processor/mod.rs [hunk 1]
```diff
@@ -514,6 +514,12 @@ pub struct BatchProcessorMetrics {
     /// Number of empty records dropped
     #[metric(unit = "{msg}")]
     dropped_empty_records: Counter<u64>,
+    /// Number of requests nacked due to inbound slot exhaustion
+    #[metric(unit = "{msg}")]
+    nacked_inbound_slots: Counter<u64>,
+    /// Number of requests nacked due to inbound slot exhaustion
+    #[metric(unit = "{msg}")]
+    nacked_outbound_slots: Counter<u64>,
```
Comment (lquerel) [inline rust/otap-dataflow/crates/core-nodes/src/processors/batch_processor/mod.rs:522]: Probably for a future PR, but we could track these two metrics in the effect handlers so that nodes don't have to implement this instrumentation manually.

I'm adding that in #2370 .

**Review by lquerel — APPROVED** [review]
LGTM

File: rust/otap-dataflow/crates/core-nodes/src/processors/batch_processor/mod.rs (hunk 1 above)
Comment (jmacd) [reply rust/otap-dataflow/crates/core-nodes/src/processors/batch_processor/mod.rs:522]: I covered this in #2386
