### PR TITLE
Attribute processor insert/update improvements

### LINKED ISSUE #2014: Inserting attribute does not function correctly when there are no existing attributes
In https://github.com/open-telemetry/otel-arrow/pull/1737 we added the ability to insert attributes using the attribute processor.

However, if the record batch to which we're inserting does not exist on the OTAP batch (e.g., if we're inserting a log attribute, but the batch has no log attributes at all to begin with), then the transformation is not properly applied:

For example, if I add a test like this to the attributes processor:

```rs
    #[test]
    fn test_insert_no_existing_attributes() {
        // Test inserting a boolean value via JSON configuration - there are no existing attributes:
        let input = build_logs_with_attrs(
            vec![], // no resource attrs
            vec![], // no scope attrs
            vec![], // no log attrs
        );

        let cfg = json!({
            "actions": [
                {"action": "insert", "key": "enabled", "value": true},
            ],
            "apply_to": ["signal"]
        });

        let metrics_registry_handle = TelemetryRegistryHandle::new();
        let controller_ctx = ControllerContext::new(metrics_registry_handle);
        let pipeline_ctx =
            controller_ctx.pipeline_context_with("grp".into(), "pipeline".into(), 0, 1, 0);

        let node = test_node("attributes-processor-insert-no-existing");
        let rt: TestRuntime<OtapPdata> = TestRuntime::new();
        let mut node_config = NodeUserConfig::new_processor_config(ATTRIBUTES_PROCESSOR_URN);
        node_config.config = cfg;
        let proc =
            create_attributes_processor(pipeline_ctx, node, Arc::new(node_config), rt.config())
                .expect("create processor");
        let phase = rt.set_processor(proc);

        phase
            .run_test(|mut ctx| async move {
                let mut bytes = BytesMut::new();
                input.encode(&mut bytes).expect("encode");
                let bytes = bytes.freeze();
                let pdata_in =
                    OtapPdata::new_default(OtlpProtoBytes::ExportLogsRequest(bytes).into());
                ctx.process(Message::PData(pdata_in))
                    .await
                    .expect("process");

                let out = ctx.drain_pdata().await;
                let first = out.into_iter().next().expect("one output").payload();

                let otlp_bytes: OtlpProtoBytes = first.try_into().expect("convert to otlp");
                let bytes = match otlp_bytes {
                    OtlpProtoBytes::ExportLogsRequest(b) => b,
                    _ => panic!("unexpected otlp variant"),
                };
                let decoded = ExportLogsServiceRequest::decode(bytes.as_ref()).expect("decode");

                let log_attrs = &decoded.resource_logs[0].scope_logs[0].log_records[0].attributes;

                println!("attrs = {:?}", log_attrs);

                // Verify the bool value was inserted correctly
                assert!(log_attrs.iter().any(|kv| kv.key == "enabled"));
                let enabled_kv = log_attrs.iter().find(|kv| kv.key == "enabled").unwrap();
                let inner_val = enabled_kv.value.as_ref().unwrap().value.as_ref().unwrap();
                match inner_val {
                    otap_df_pdata::proto::opentelemetry::common::v1::any_value::Value::BoolValue(b) => {
                        assert!(*b);
                    }
                    _ => panic!("expected BoolValue, got {:?}", inner_val),
                }
                assert!(log_attrs.iter().any(|kv| kv.key == "existing"));
            })
            .validate(|_| async move {});
    }
```

this will print:
```
running 1 test
attrs = []

thread 'attributes_processor::tests::test_insert_no_existing_attributes' (4589612) panicked at crates/otap/src/attributes_processor.rs:1121:17:
assertion failed: log_attrs.iter().any(|kv| kv.key == "enabled")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test attributes_processor::tests::test_insert_no_existing_attributes ... FAILED
```

### PR DESCRIPTION
**Pull request by albertlockett**
# Change Summary

This PR integrates the optimized `upsert_attributes` function that was added in https://github.com/open-telemetry/otel-arrow/pull/2379 into the code path used for by the attributes_processor (this got moved into the pdata crate from query-engine)

Before this change, our upserts and inserts were handled by:
- treating upserts for existing attributes as deletes while performing rename & delete
- building new record batch for the insert/upsert and concatenating it to the previous record batch, while aligning schemas

This optimized code doesn't do this delete for the existing upsert attributes, and it tries to merge the upserts/inserts with the buffers from the previous attribute columns in an optimized way.

This PR also fixes a handful of issues with the current insert/upsert implementation
- if some row didn't have existing attributes, no new ones would be created
- the string/int values columns would get expanded from their dict type to the native non-dict encoded array

The way we invoke the attribute transform has been simplified as well, and all the details of selecting the correct record batch, creating it if it doesn't exist, ensuring the parent rows have the required right IDs, etc are all encapsulated in a simpler interface:

```rs
let collect_stats = true; // or false, as you wish it
let stats = apply_attribute_transform(&mut otap_batch, attrs_payload_type, &self.transform, collect_stats)?;
```

## What issue does this PR close?

* Closes #2014 
* Closes https://github.com/open-telemetry/otel-arrow/issues/2350

## How are these changes tested?

many unit tests

## Are there any user-facing changes?

No

### CODE REVIEW

**Comment by albertlockett** [comment]
```
upsert_attributes/upsert_with_delete/rows=128,dict_keys=true
                        time:   [5.1141 µs 5.1373 µs 5.1620 µs]
                        change: [−41.903% −41.596% −41.311%] (p = 0.00 < 0.05)
                        Performance has improved.

upsert_attributes/upsert_multiple_keys/rows=128,dict_keys=true
                        time:   [7.2244 µs 7.2718 µs 7.3155 µs]
                        change: [−30.833% −30.419% −29.943%] (p = 0.00 < 0.05)
                        Performance has improved.

upsert_attributes/upsert_new_key/rows=1536,dict_keys=true
                        time:   [7.1654 µs 7.1924 µs 7.2195 µs]
                        change: [−92.456% −92.406% −92.357%] (p = 0.00 < 0.05)
                        Performance has improved.

upsert_attributes/upsert_existing_key/rows=1536,dict_keys=true
                        time:   [13.089 µs 13.124 µs 13.162 µs]
                        change: [−84.088% −83.990% −83.894%] (p = 0.00 < 0.05)
                        Performance has improved.

upsert_attributes/upsert_with_delete/rows=1536,dict_keys=true
                        time:   [20.958 µs 21.002 µs 21.049 µs]
                        change: [−68.737% −68.617% −68.489%] (p = 0.00 < 0.05)
                        Performance has improved.

upsert_attributes/upsert_multiple_keys/rows=1536,dict_keys=true
                        time:   [26.377 µs 26.441 µs 26.504 µs]
                        change: [−69.707% −69.541% −69.386%] (p = 0.00 < 0.05)
                        Performance has improved.

upsert_attributes/upsert_new_key/rows=8192,dict_keys=true
                        time:   [25.152 µs 25.244 µs 25.339 µs]
                        change: [−96.379% −96.358% −96.337%] (p = 0.00 < 0.05)
                        Performance has improved.

upsert_attributes/upsert_existing_key/rows=8192,dict_keys=true
                        time:   [56.325 µs 56.466 µs 56.607 µs]
                        change: [−90.779% −90.739% −90.700%] (p = 0.00 < 0.05)
                        Performance has improved.

upsert_attributes/upsert_with_delete/rows=8192,dict_keys=true
                        time:   [92.404 µs 92.523 µs 92.658 µs]
                        change: [−80.467% −80.400% −80.328%] (p = 0.00 < 0.05)
                        Performance has improved.

upsert_attributes/upsert_multiple_keys/rows=8192,dict_keys=true
                        time:   [107.05 µs 107.55 µs 108.17 µs]
                        change: [−81.818% −81.729% −81.619%] (p = 0.00 < 0.05)
                        Performance has improved.
```

File: rust/otap-dataflow/crates/pdata/src/otap/transform/upsert_attributes.rs [hunk 1]
```diff
@@ -371,14 +413,36 @@ fn build_combined_mask(resolved: &[ResolvedUpsert<'_>]) -> Result<BooleanArray>
...
+    if matches!(existing_col.data_type(), DataType::Dictionary(_, _)) {
+        if let Some(merged_dict_column) =
+            merge_parent_id_column_dict(&existing_col, resolved, total_num_inserts)?
+        {
+            return Ok((
+                Field::new(
+                    consts::PARENT_ID,
+                    merged_dict_column.data_type().clone(),
+                    false,
+                ),
```
Comment (lquerel) [inline rust/otap-dataflow/crates/pdata/src/otap/transform/upsert_attributes.rs]: Don't we still need the metadata potentially present in the original `field`?

Comment (albertlockett) [reply rust/otap-dataflow/crates/pdata/src/otap/transform/upsert_attributes.rs]: oof yeah good catch. Fixed in a572fdd41. Thanks again @lquerel
