### PR TITLE
UpDownCounter as cumulative only, fixes syslog panic

### LINKED ISSUE #2275: UpDownCounter semantics, Syslog panic
#[test]
    fn up_down_counter_not_reset_by_clear_values() {
        use otap_df_telemetry::metrics::MetricSetHandler;

        let mut metrics = SyslogCefReceiverMetrics::default();

        // Connection opened
        metrics.tcp_connections_active.inc();
        assert_eq!(metrics.tcp_connections_active.get(), 1);

        // Periodic telemetry collection resets values, so we are back to 0.
        metrics.clear_values();

        // Connection closed and try to dec()— this panics!
        metrics.tcp_connections_active.dec();
        assert_eq!(metrics.tcp_connections_active.get(), 0);
    }

### PR DESCRIPTION
**Pull request by cijothomas**
Fixes #2275. I am unsure of other side-effects, so need sing-offs from all!

### CODE REVIEW

File: rust/otap-dataflow/crates/telemetry-macros/src/lib.rs [hunk 1]
```diff
@@ -205,7 +205,7 @@ pub fn derive_metric_set_handler(input: TokenStream) -> TokenStream {
                                         otap_df_telemetry::descriptor::Instrument::UpDownCounter
                                     ),
                                         quote!(Some(
-                                            otap_df_telemetry::descriptor::Temporality::Delta
+                                            otap_df_telemetry::descriptor::Temporality::Cumulative
```
Comment (jmacd) [inline rust/otap-dataflow/crates/telemetry-macros/src/lib.rs:208]: Looks good.

**Review by jmacd — APPROVED** [review]
