### PR TITLE
Emit warning and skip unconnected nodes during engine build

### LINKED ISSUE #2012: Engine startup behavior with unconnected nodes
Would like to raise a question about some observed behavior differing from Go Collector with respect to handling of unconnected components/nodes.

The following configuration produces an engine startup error:

```yaml
settings:
  default_pipeline_ctrl_msg_channel_size: 100
  default_node_ctrl_msg_channel_size: 100
  default_pdata_channel_size: 100

nodes:
  syslog_cef_receiver:
    kind: receiver
    plugin_urn: "urn:otel:syslog_cef:receiver"
    out_ports:
      out_port:
        destinations:
          - noop_exporter
        dispatch_strategy: round_robin
    config:
      listening_addr: "127.0.0.1:5514"
      protocol: tcp

  batch_proc:
    kind: processor
    plugin_urn: "urn:otel:batch:processor"
    out_ports:
      out_port:
        destinations:
          - noop_exporter
        dispatch_strategy: round_robin
    config:
      otap:
        min_size: 1
        sizer: items
      flush_timeout: 5s

  noop_exporter:
    kind: exporter
    plugin_urn: "urn:otel:noop:exporter"  

```

Error:
> 2026-02-10T16:53:09.288Z  ERROR otap-df-state::state.observed_error (crates/state/src/store.rs:189):  [observed_event=EngineEvent { key: DeployedPipelineKey { pipeline_group_id: "default_pipeline_group", pipeline_id: "default_pipeline", core_id: 0 }, node_id: None, node_kind: None, time: SystemTime { tv_sec: 1770742389, tv_nsec: 287943125 }, type: Error(RuntimeError(Node { node: "batch_proc", node_kind: Processor, error_kind: "configuration", message: "The pdata receiver must be defined at this stage", source: None })), message: Some("Pipeline encountered a runtime error.") }]
Pipeline failed to run: Pipeline runtime error: A processor error occurred in node batch_proc (configuration): The pdata receiver must be defined at this stage

Should this prevent engine startup or is it better to emit a WARN message about the unconnected node and proceed?

### PR DESCRIPTION
**Pull request by drewrelmas**
# Change Summary

Add a pre-processing step at the start of pipeline build that gracefully removes unconnected nodes from the incoming `PipelineConfig`.

Input with unconnected nodes:
```yaml
nodes:
  unconnected_receiver:
    kind: receiver
    plugin_urn: "urn:otel:syslog_cef:receiver"
    out_ports:
    config:
      listening_addr: "127.0.0.1:5514"
      protocol: tcp

  connected_receiver:
    kind: receiver
    plugin_urn: "urn:otel:syslog_cef:receiver"
    out_ports:
      out_port:
        destinations:
          - connected_proc
        dispatch_strategy: round_robin
    config:
      listening_addr: "127.0.0.1:5514"
      protocol: tcp

  unconnected_proc:
    kind: processor
    plugin_urn: "urn:otel:batch:processor"
    out_ports:
      out_port:
        destinations:
          - connected_proc
        dispatch_strategy: round_robin
    config:
      otap:
        min_size: 1
        sizer: items
      flush_timeout: 5s

  connected_proc:
    kind: processor
    plugin_urn: "urn:otel:debug:processor"
    out_ports:
      out_port:
        destinations:
          - noop_exporter
        dispatch_strategy: round_robin
    config:
      verbosity: detailed
      mode: signal

  noop_exporter:
    kind: exporter
    plugin_urn: "urn:otel:noop:exporter"  
```

Output (confirmed that log was able to pass through remaining connected nodes with debug processor):
```log
2026-02-11T19:01:57.699Z  INFO  otap-df-engine::pipeline.build.unconnected_node.removed: Removed unconnected node from pipeline. [pipeline_group_id=default_pipeline_group, pipeline_id=default_pipeline, core_id=0, node_id=unconnected_receiver, node_kind=receiver] entity/pipeline.attrs: pipeline.id=default_pipeline pipeline.group.id=default_pipeline_group core.id=0 numa.node.id=0 process.instance.id=AGOE4FHDDZ7ZBMHGEFGLWWBHPE host.id=CPC-drewr-ZFPSN container.id=
2026-02-11T19:01:57.706Z  INFO  otap-df-admin::endpoint.start: Admin HTTP server listening [bind_address=127.0.0.1:8080]
2026-02-11T19:01:57.701Z  INFO  otap-df-engine::pipeline.build.unconnected_node.removed: Removed unconnected node from pipeline. [pipeline_group_id=default_pipeline_group, pipeline_id=default_pipeline, core_id=0, node_id=unconnected_proc, node_kind=processor] entity/pipeline.attrs: pipeline.id=default_pipeline pipeline.group.id=default_pipeline_group core.id=0 numa.node.id=0 process.instance.id=AGOE4FHDDZ7ZBMHGEFGLWWBHPE host.id=CPC-drewr-ZFPSN container.id=
2026-02-11T19:01:57.702Z  WARN  otap-df-engine::pipeline.build.unconnected_nodes: Some pipeline nodes were removed because they had no active incoming or outgoing edges. These nodes will not participate in data processing. Check pipeline configuration if this is unintentional. [pipeline_group_id=default_pipeline_group, pipeline_id=default_pipeline, core_id=0, removed_count=2] entity/pipeline.attrs: pipeline.id=default_pipeline pipeline.group.id=default_pipeline_group core.id=0 numa.node.id=0 process.instance.id=AGOE4FHDDZ7ZBMHGEFGLWWBHPE host.id=CPC-drewr-ZFPSN container.id=
2026-02-11T19:01:57.725Z  INFO  otap-df-otap::receiver.start: Starting Syslog/CEF Receiver [protocol=Tcp, listening_addr=127.0.0.1:5514] entity/node.attrs: node.id=connected_receiver node.urn=urn:otel:syslog_cef:receiver node.type=receiver pipeline.id=default_pipeline pipeline.group.id=default_pipeline_group core.id=0 numa.node.id=0 process.instance.id=AGOE4FHDDZ7ZBMHGEFGLWWBHPE host.id=CPC-drewr-ZFPSN container.id=

Received 1 resource logs
Received 1 log records
Received 0 events
LogRecord #0:
   -> ObservedTimestamp: 1770836524675426978
   -> Timestamp: 1770836524000000000
   -> SeverityText: INFO
   -> SeverityNumber: 9
   -> Attributes:
      -> syslog.facility: 16
      -> syslog.severity: 6
      -> syslog.host_name: securityhost
      -> syslog.tag: myapp[1234]
      -> syslog.app_name: myapp
      -> syslog.process_id: 1234
      -> syslog.content: User admin logged in from 10.0.0.1 successfully [test_id=234tg index=1]
   -> Trace ID:
   -> Span ID:
   -> Flags: 0
```

Input with no connected nodes:
```yaml
nodes:
  recv:
    kind: receiver
    plugin_urn: "urn:test:a:receiver"
    config: {}
  proc:
    kind: processor
    plugin_urn: "urn:test:b:processor"
    out_ports:
      out:
        destinations: [exp]
        dispatch_strategy: round_robin
    config: {}
  exp:
    kind: exporter
    plugin_urn: "urn:test:c:exporter"
    config: {}
```

Output:
```log
2026-02-11T19:00:02.759Z  INFO  otap-df-engine::pipeline.build.unconnected_node.removed: Removed unconnected node from pipeline. [pipeline_group_id=default_pipeline_group, pipeline_id=default_pipeline, core_id=0, node_id=proc, node_kind=processor]
2026-02-11T19:00:02.759Z  INFO  otap-df-engine::pipeline.build.unconnected_node.removed: Removed unconnected node from pipeline. [pipeline_group_id=default_pipeline_group, pipeline_id=default_pipeline, core_id=0, node_id=recv, node_kind=receiver]
2026-02-11T19:00:02.759Z  INFO  otap-df-engine::pipeline.build.unconnected_node.removed: Removed unconnected node from pipeline. [pipeline_group_id=default_pipeline_group, pipeline_id=default_pipeline, core_id=0, node_id=exp, node_kind=exporter]
2026-02-11T19:00:02.759Z  WARN  otap-df-engine::pipeline.build.unconnected_nodes: Some pipeline nodes were removed because they had no active incoming or outgoing edges. These nodes will not participate in data processing. Check pipeline configuration if this is unintentional. [pipeline_group_id=default_pipeline_group, pipeline_id=default_pipeline, core_id=0, removed_count=3]
2026-02-11T19:00:02.759Z  ERROR otap-df-state::state.observed_error: [observed_event=EngineEvent { key: DeployedPipelineKey { pipeline_group_id: "default_pipeline_group", pipeline_id: "default_pipeline", core_id: 0 }, node_id: None, node_kind: None, time: SystemTime { tv_sec: 1770836402, tv_nsec: 759880158 }, type: Error(RuntimeError(Pipeline { error_kind: "EmptyPipeline", message: "Pipeline has no connected nodes after removing unconnected entries — check pipeline configuration", source: None })), message: Some("Pipeline encountered a runtime error.") }]
2026-02-11T19:00:02.760Z  ERROR otap-df-state::state.report_failed: [error=InvalidTransition { phase: Starting, event: Error(RuntimeError(Pipeline { error_kind: "EmptyPipeline", message: "Pipeline has no connected nodes after removing unconnected entries — check pipeline configuration", source: None })), message: "event not valid for current phase" }]
2026-02-11T19:00:02.760Z  INFO  otap-df-admin::endpoint.start: Admin HTTP server listening [bind_address=127.0.0.1:8080]
Pipeline failed to run: Pipeline runtime error: Pipeline has no connected nodes after removing unconnected entries — check pipeline configuration
```

## What issue does this PR close?

* Closes #2012

## How are these changes tested?

Unit tests and local engine runs.

## Are there any user-facing changes?

1. Engine is now more flexible and does not crash with unconnected nodes present in the config.
2. Engine provides visible error if there are no nodes provided instead of starting up successfully.

### CODE REVIEW

File: rust/otap-dataflow/crates/engine/src/lib.rs [hunk 1]
```diff
@@ -379,6 +379,22 @@ impl<PData: 'static + Clone + Debug> PipelineFactory<PData> {
...
+        let unconnected = config.remove_unconnected_nodes();
+        for (node_id, node_kind) in &unconnected {
+            let kind: Cow<'static, str> = (*node_kind).into();
+            otel_warn!(
+                "pipeline.build.unconnected_node",
+                pipeline_group_id = pipeline_group_id.as_ref(),
+                pipeline_id = pipeline_id.as_ref(),
+                core_id = core_id,
+                node_id = node_id.as_ref(),
+                node_kind = kind.as_ref(),
```
Comment (cijothomas) [inline rust/otap-dataflow/crates/engine/src/lib.rs:395]: do include a message="Removed unconnected node from the pipeline. Engine will continue running." /similar

File: rust/otap-dataflow/crates/config/src/pipeline.rs [hunk 2]
```diff
@@ -1766,4 +1857,140 @@ mod tests {
...
+            removed_ids.contains(&"orphan_exp"),
+            "should remove orphan exporter, got: {removed_ids:?}"
+        );
+        assert!(config.nodes().contains_key("recv"));
+        assert!(config.nodes().contains_key("connected_exp"));
+    }
+
+    #[test]
+    fn test_remove_unconnected_cascading_removal() {
+        // 3-level cascade: orphan_proc1 has no incoming edges so it is removed
```
Comment (cijothomas) [inline rust/otap-dataflow/crates/config/src/pipeline.rs:1987]: ❤️ these tests!
nit: could we use the yaml as input instead of programatic config, so its easier to see what scenario are we testing.

File: rust/otap-dataflow/crates/config/src/pipeline.rs [hunk 3]
```diff
@@ -1766,4 +1857,140 @@ mod tests {
...
+            .build(PipelineType::Otap, "g", "p")
+            .unwrap();
+
+        let removed = config.remove_unconnected_nodes();
+        assert!(
+            removed.is_empty(),
+            "fully connected pipeline should have no removals, got: {removed:?}"
+        );
+        assert_eq!(config.nodes().len(), 3);
+    }
```
Comment (cijothomas) [inline rust/otap-dataflow/crates/config/src/pipeline.rs:2086]: can we add a test where everything was disconnected and removed? is that going to fail engine startup, or we still startup?

File: rust/otap-dataflow/crates/engine/src/lib.rs [hunk 4]
```diff
@@ -379,6 +379,22 @@ impl<PData: 'static + Clone + Debug> PipelineFactory<PData> {
         );
         let _enter = span.enter();
 
+        // Remove unconnected nodes before building the pipeline.
+        // Nodes that have no incoming or outgoing connections are filtered out
+        // with a warning instead of causing a startup failure.
+        let unconnected = config.remove_unconnected_nodes();
```
Comment (cijothomas) [inline rust/otap-dataflow/crates/engine/src/lib.rs:385]: minor:
do INFO level log inside the remove() method detailing what was removed.
and if there was >0 nodes removed, do a WARN here that some nodes were removed, and the count of them and the impact.

**Review by cijothomas — APPROVED** [review]
LGMT, left some minor suggestions.

File: rust/otap-dataflow/crates/config/src/pipeline.rs (hunk 2 above)
Comment (drewrelmas) [reply rust/otap-dataflow/crates/config/src/pipeline.rs:1987]: Done

File: rust/otap-dataflow/crates/engine/src/lib.rs (hunk 1 above)
Comment (drewrelmas) [reply rust/otap-dataflow/crates/engine/src/lib.rs:395]: Added relevant messages

File: rust/otap-dataflow/crates/config/src/pipeline.rs (hunk 3 above)
Comment (drewrelmas) [reply rust/otap-dataflow/crates/config/src/pipeline.rs:2086]: I added this test. Engine actually didn't fail with 0 nodes before, I added a new `Error` and DO fail in this case. Would like to get extra opinions on if this is correct behavior, but it feels correct to me.

File: rust/otap-dataflow/crates/engine/src/lib.rs (hunk 4 above)
Comment (drewrelmas) [reply rust/otap-dataflow/crates/engine/src/lib.rs:385]: Updated to have multiple Infos and one Warn, but all outside of the remove() func. Cannot easily add telemetry dependency to config crate because of circular dependency.

File: rust/otap-dataflow/crates/engine/src/lib.rs [hunk 5]
```diff
@@ -379,6 +379,38 @@ impl<PData: 'static + Clone + Debug> PipelineFactory<PData> {
...
+                core_id = core_id,
+                removed_count = unconnected.len(),
+            );
+        }
+
+        // If every node was removed, the pipeline config is broken — fail early.
+        if config.nodes().is_empty() {
+            return Err(Error::EmptyPipeline);
+        }
+
```
Comment (drewrelmas) [inline rust/otap-dataflow/crates/engine/src/lib.rs:413]: This is a new behavior change, but feels correct to me.

File: rust/otap-dataflow/crates/config/src/pipeline.rs (hunk 2 above)
Comment (cijothomas) [reply rust/otap-dataflow/crates/config/src/pipeline.rs:1987]: perfect! We can introduce (in future) a `config validate` option like collector already has!

File: rust/otap-dataflow/crates/engine/src/error.rs [hunk 6]
```diff
@@ -374,6 +374,12 @@ pub enum Error {
         message: String,
     },
 
+    /// All nodes were removed from the pipeline (none are connected).
```
Comment (cijothomas) [inline rust/otap-dataflow/crates/engine/src/error.rs:377]: do we need to distinguish between
1. There were nodes, but all were disconnected. We cleaned them up and now we have no nodes at all.
2. There were no nodes to begin with.

(not a blocker and not critical)

File: rust/otap-dataflow/crates/engine/src/lib.rs (hunk 5 above)
Comment (cijothomas) [reply rust/otap-dataflow/crates/engine/src/lib.rs:413]: agree.

File: rust/otap-dataflow/crates/engine/src/error.rs (hunk 6 above)
Comment (drewrelmas) [reply rust/otap-dataflow/crates/engine/src/error.rs:377]: I'm not sure it matters as the end result is the same, engine fails to start. The other telemetry added should indicate cause.

Comment (cijothomas) [reply rust/otap-dataflow/crates/engine/src/error.rs:377]: correct!

File: rust/otap-dataflow/crates/config/src/pipeline.rs [hunk 7]
```diff
@@ -336,6 +336,92 @@ impl PipelineNodes {
...
+
+            // Clean up references to removed nodes from remaining nodes' destinations
+            let removed_ids: HashSet<&NodeId> = to_remove.iter().map(|(id, _)| id).collect();
+            for node_config in self.0.values_mut() {
+                let mut updated = (**node_config).clone();
+                for edge in updated.out_ports.values_mut() {
+                    edge.destinations.retain(|dest| !removed_ids.contains(dest));
+                }
+                *node_config = Arc::new(updated);
+            }
```
Comment (lalitb) [inline rust/otap-dataflow/crates/config/src/pipeline.rs:426]: nit - This clones every surviving node each pass even if it doesn't reference any removed node. Could skip the clone when nothing changes.
Startup-only so not urgent, but cheap win.

Comment (drewrelmas) [reply rust/otap-dataflow/crates/config/src/pipeline.rs:426]: Updated
