### PR TITLE
Pipeline/group/engine policy precedence: prevent against misuse of unresolved policies

### LINKED ISSUE #2389: Pipeline-level policy overrides engine-level policy
### Pre-filing checklist

- [x] I searched existing issues and didn't find a duplicate

### Component(s)

Rust OTAP dataflow (rust/otap-dataflow/)

### Bug Description

Like #2154 but impacting telemetry. We need an `Option<>` for policy fields so they merge correctly, otherwise an omitted value in the pipeline-level will override the engine-level because `#[serde(default)]`.

This likely also impacts channel capacity and health settings. Note: there are correct `resolve()` methods in place, but because the fields were `pub` it is possible to access them incorrectly.

### Steps to Reproduce

See #2154, for telemetry policies.

### Expected Behavior

These values take effect when not set in the pipeline or group level.
```
policies:
  channel_capacity:
    ...
  telemetry:
    channel_metrics: detailed
```

### Actual Behavior

The detailed metrics setting does not take.

### OTel-Arrow Version

main

### Environment

_No response_

### Configuration

```yaml

```

### Log Output

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jmacd**
# Change Summary

Like #2154 but for the other three policy fields. Make all fields Option types. Adds a ResolvedPolicies type which strips the Options after resolving. There was existing resolve code, but it was not used consistently: this was observed for the `telemetry` policy.

## What issue does this PR close?

Fixes #2389.

## How are these changes tested?

One new test. The `configs/internal-telemetry.yaml` configuration is modified to show the problem. Before the fix, no duration metrics. After the fix, duration metrics, as set by the top-level policy.

### CODE REVIEW

File: rust/otap-dataflow/crates/config/src/engine.rs [hunk 1]
```diff
@@ -533,11 +534,137 @@ groups:
...
         );
         assert_eq!(
-            p3_resolved.policies.effective_resources().core_allocation,
+            p3_resolved.policies.resources.core_allocation,
             crate::policy::CoreAllocation::CoreCount { count: 9 }
         );
     }
 
+    #[test]
+    fn resolve_policies_inherit_from_parent_scope() {
```
Comment (gouslu) [inline rust/otap-dataflow/crates/config/src/engine.rs:543]: are there any tests for when inheritance comes partially from engine level and partially from group level? if not, it is worth adding.

**Comment by gouslu** [comment]
If applicable, there should be a test where partial configration from different tiers are taken in a way that it validates the fact that they are merged at the lowest level. And there should also be a test that validates both they are merged and the inner value wins and overrides an outer value.

File: rust/otap-dataflow/crates/config/src/engine.rs (hunk 1 above)
Comment (jmacd) [reply rust/otap-dataflow/crates/config/src/engine.rs:543]: Done
