### PR TITLE
Standardization of urns, validation and usage

### LINKED ISSUE #1831: Proposal 4 - Standardization of the URN format [config=model-v1]
I propose to use the following canonical format for node identifiers: `urn:<namespace>:<id>:<kind>`

- `otel` is a reserved namespace identifier.
- A namespace is typically a vendor name, or a vendor + product name.
- The URN uniquely identifies a node type and is used as the key for:
  - configuration parsing
  - registry lookup
  - control API interactions

## Naming rules

To ensure unambiguous parsing and long-term stability, the following rules apply:

- The `:` character is reserved as a structural separator in the URN format.
- As a consequence, `:` is prohibited in the following components:
  - `namespace`
  - `id`
  - `kind`
- Components MUST NOT contain `:` and MUST be treated as opaque identifiers.
- Implementations MUST reject URNs that violate these rules.

**To improve configuration readability and ergonomics, a shortcut form is proposed for pure OpenTelemetry nodes.**

Shortcut rules:

- A node identifier MAY be expressed in one of two forms:
  - full form:  
    ```
    urn:<namespace>:<id>:<kind>
    ```
  - shortcut form (OTel only):  
    ```
    <id>:<kind>
    ```
- The shortcut form is only allowed for the `otel` namespace.
- When the shortcut form is used, the implementation MUST expand it to: `urn:otel:<id>:<kind>` before validation, resolution, and registry lookup.
- The shortcut form MUST NOT be accepted for any namespace other than `otel`.
- Identifiers starting with `urn:` are always interpreted as fully-qualified URNs.

This ensures:
- zero ambiguity
- a single canonical internal representation
- improved UX for the most common node types

## Migration table

| current urn | target urn | shortcut | changed |
|--|--|--|--|
| urn:otel:otlp:receiver | urn:otel:otlp:receiver | otlp:receiver |   |
| urn:otel:otap:receiver | urn:otel:otap:receiver | otap:receiver |   |
| urn:otel:syslog_cef:receiver | urn:otel:syslog_cef:receiver | syslog_cef:receiver |   |
| urn:otel:otap:fake_data_generator:receiver | urn:otel:traffic_generator:receiver | traffic_generator:receiver | x |
| urn:otap:processor:attribute_processor | urn:otel:attribute:processor | attribute:processor | x |
| urn:otel:filter:processor | urn:otel:filter:processor | filter:processor |   |
| urn:otel:batch:processor | urn:otel:batch:processor | batch:processor |   |
| urn:otel:debug:processor | urn:otel:debug:processor | debug:processor |   |
| urn:otel:condense_attributes:processor | urn:otel:condense_attributes:processor | condense_attributes:processor |   |
| urn:otel:retry:processor | urn:otel:retry:processor | retry:processor |   |
| urn:otap:processor:signal_type_router | urn:otel:type_router:processor | type_router:processor | x |
| urn:otel:transform:processor | urn:otel:transform:processor | transform:processor |   |
| urn:otel:otap:parquet:exporter | urn:otel:parquet:exporter | parquet:exporter | x |
| urn:otel:error:exporter | urn:otel:error:exporter | error:exporter |   |
| urn:otel:otlp:exporter | urn:otel:otlp:exporter | otlp:exporter |   |
| urn:otel:otap:exporter | urn:otel:otap:exporter | otap:exporter |   |
| urn:otel:noop:exporter | urn:otel:noop:exporter | noop:exporter |   |
| urn:otel:otap:perf:exporter | urn:otel:perf:exporter | perf:exporter | x |
| not implemented | urn:otel:named_channel:receiver | named_channel:receiver | x | 
| not implemented | urn:otel:named_channel:exporter | named_channel:exporter | x | 
| urn:otel:azuremonitor:exporter | urn:microsoft_azure:monitor:exporter | N/A | x |
| urn:otel:recordset_kql:processor | urn:microsoft:recordset_kql:processor | N/A | x |

### PR DESCRIPTION
**Pull request by daviddahl**
# Change Summary

  Standardized otap-df-otap node URNs to the canonical urn:<namespace>:<id>:<kind> format, added strict parsing/normalization
  (including OTel shortcut support), updated component constants/configs/templates/docs to match, and documented otelcol config
  compatibility design and URN rules.

  ## What issue does this PR close?

  - Closes #1831

  ## How are these changes tested?

  - cargo test (per local confirmation)
  - Added unit/config tests for URN normalization and legacy URN rejection in otap_df_config

  ## Are there any user-facing changes?

  Yes. Configuration now enforces canonical URN format and accepts the OTel shortcut form; legacy URNs are rejected with a doc-linked
  error message.

### CODE REVIEW

File: rust/otap-dataflow/crates/config/src/urn.rs [hunk 1]
```diff
@@ -13,106 +13,145 @@ use crate::error::Error;
...
+            .map(|(_, tail)| tail)
+            .unwrap_or_default()
+            .trim();
+        let segs: Vec<&str> = rest.split(':').collect();
+        if segs.len() != EXPECTED_SEGMENT_COUNT + 1 {
+            return Err(invalid_plugin_urn(
+                raw,
+                "expected exactly 3 segments in `urn:<namespace>:<id>:<kind>`".to_string(),
+            ));
+        }
```
Comment (lquerel) [inline rust/otap-dataflow/crates/config/src/urn.rs]: Could be simplified by splitting the raw urn on the `:` separator and then process the two valid branches:
- 2 parts: <id>:<kind>
- 4 parts: urn:<namespace>:<id>:<kind>
- all the other split configurations are invalid and must return an error.

File: rust/otap-dataflow/crates/config/src/urn.rs [hunk 2]
```diff
@@ -13,106 +13,145 @@ use crate::error::Error;
...
+
+    let segs: Vec<&str> = raw.split(':').collect();
+    validate_segments(raw, "otel", &segs)?;
+    let (id, kind) = split_segments(raw, &segs)?;
+    validate_kind(raw, kind, expected_suffix)?;
+    Ok(format!("urn:otel:{id}:{kind}"))
+}
+
+/// Validate a plugin URN against the expected node kind.
 pub fn validate_plugin_urn(raw: &str, expected_kind: NodeKind) -> Result<(), Error> {
```
Comment (lquerel) [inline rust/otap-dataflow/crates/config/src/urn.rs]: Not sure this function is still really useful

File: rust/otap-dataflow/docs/urns.md [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+
+```
+otlp:receiver
+debug:processor
+```
+
+## Legacy URNs
+
+Legacy URN formats (for example, `urn:otap:processor:<name>` or any URN with more
+than two segments after the namespace) are not accepted and will fail validation.
```
Comment (lquerel) [inline rust/otap-dataflow/docs/urns.md]: I suggest to remove this section.

File: rust/otap-dataflow/crates/config/src/urn.rs (hunk 2 above)
Comment (daviddahl) [reply rust/otap-dataflow/crates/config/src/urn.rs]: Updated per feedback: removed the extra helper and kept the original validate_plugin_urn API name. It now performs validation + normalization and returns the canonical URN, so there’s a single entry point.

File: rust/otap-dataflow/configs/fake-kql-debug-noop.yaml [hunk 4]
```diff
@@ -19,7 +19,7 @@ nodes:
 
   kql:
     kind: processor
-    plugin_urn: "urn:otel:recordset_kql:processor"
+    plugin_urn: "urn:microsoft:recordset_kql:processor"
```
Comment (jmacd) [inline rust/otap-dataflow/configs/fake-kql-debug-noop.yaml:22]: :+1:

File: rust/otap-dataflow/crates/otap/src/signal_type_router.rs [hunk 5]
```diff
@@ -29,7 +29,7 @@ use serde::{Deserialize, Serialize};
 use std::sync::Arc;
 
 /// URN for the SignalTypeRouter processor
-pub const SIGNAL_TYPE_ROUTER_URN: &str = "urn:otap:processor:signal_type_router";
+pub const SIGNAL_TYPE_ROUTER_URN: &str = "urn:otel:type_router:processor";
```
Comment (jmacd) [inline rust/otap-dataflow/crates/otap/src/signal_type_router.rs:32]: I would prefer this be `signal_router`, I'm worried "type" loses the important part.

**Review by jmacd — APPROVED** [review]

**Comment by daviddahl** [comment]
@jmacd thanks for the review. Are you able to trigger the full performance test suite for this PR?

**Comment by albertlockett** [comment]
> @jmacd thanks for the review. Are you able to trigger the full performance test suite for this PR?

@daviddahl I think it has already run - is this the suite you are asking about?
https://github.com/open-telemetry/otel-arrow/actions/runs/21718181386/job/62640048448?pr=1948

**Comment by daviddahl** [comment]
> > @jmacd thanks for the review. Are you able to trigger the full performance test suite for this PR?
> 
> @daviddahl I think it has already run - is this the suite you are asking about? https://github.com/open-telemetry/otel-arrow/actions/runs/21718181386/job/62640048448?pr=1948

I thought this was the more comprehensive perf suitr? https://github.com/open-telemetry/otel-arrow/actions/runs/21718181386/job/62640048868?pr=1948
