### PR TITLE
fix: improve reliability of test_durable_buffer_recovery_after_outage

### LINKED ISSUE #1975: Flaky test: test_durable_buffer_recovery_after_outage
Some PR checks ([example](https://github.com/open-telemetry/otel-arrow/actions/runs/21727002917/job/62671602009?pr=1961#step:11:2595)) have been failing due to flaky behavior in `test_durable_buffer_recovery_after_outage`:

```
    thread 'test_durable_buffer_recovery_after_outage' (208) panicked at crates\otap\tests\durable_buffer_processor_tests.rs:570:5:
    Recovery should deliver at least 35 items (25+10), got 20
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This test is subject to timing issues and should be more deterministic.

### PR DESCRIPTION
**Pull request by AaronRM**
# Change Summary

Improve the reliability of `test_durable_buffer_recovery_after_outage` so that it is not subject to minor timing differences across runs that may lead to test failure. Make test more precise by validating the exact number of signals persisted and received by the exporter.

## What issue does this PR close?

* Closes #1975

## How are these changes tested?

* Code inspection, manually running the test to attempt failure repro.

## Are there any user-facing changes?

No, this is change only affects test code.

### CODE REVIEW

File: rust/otap-dataflow/crates/otap/tests/durable_buffer_processor_tests.rs [hunk 1]
```diff
@@ -379,6 +381,56 @@ where
...
+                    SegmentReader::open(e.path())
+                        .map(|reader| {
+                            reader
+                                .streams()
+                                .iter()
+                                .filter(|s| s.slot_id.raw() == slot_id_raw)
+                                .map(|s| s.row_count)
+                                .sum::<u64>()
+                        })
+                        .unwrap_or(0)
```
Comment (ThomsonTan) [inline rust/otap-dataflow/crates/otap/tests/durable_buffer_processor_tests.rs:414]: Log the error from `SegmentReader::open(...)` before `.unwrap_or(0)` instead of returning 0 silently?

Comment (AaronRM) [reply rust/otap-dataflow/crates/otap/tests/durable_buffer_processor_tests.rs:414]: In general I would agree, but in this case we are in test code which is expected to hit errors (since it is reading from segment files that are also being written to). I added a comment explaining why we are ignoring error results.

**Comment by jmacd** [comment]
The test failure is a flake (port binding).
