### PR TITLE
fix: OTAP streams persistent in the OTAP Exporter

### LINKED ISSUE #1064: Make OTAP streams persistent in the OTAP Exporter
Currently, an OTAP producer/stream is created for each message received by the exporter, which is suboptimal both for compression rate and overall performance.

### PR DESCRIPTION
**Pull request by albertlockett**
closes #1064 

Fixes the OTAP exporter so we stop sending just one message per stream

### CODE REVIEW

File: rust/otap-dataflow/crates/otap/src/otap_exporter.rs [hunk 1]
```diff
@@ -158,115 +161,266 @@ impl local::Exporter<OtapPdata> for OTAPExporter {
                 .send_compressed(encoding)
                 .accept_compressed(encoding);
         }
+
+        // TODO comment on the purpose of these
+        // TODO import so can use as just "channel" here
+        let (logs_sender, logs_receiver) = tokio::sync::mpsc::channel(64);
```
Comment (lquerel) [inline rust/otap-dataflow/crates/otap/src/otap_exporter.rs]:
```suggestion
        // TODO import so can use as just "channel" here
        // TODO check if we can use our local channel in conjonction with a spawn_local.
        let (logs_sender, logs_receiver) = tokio::sync::mpsc::channel(64);
```

File: rust/otap-dataflow/crates/otap/src/otap_exporter.rs [hunk 2]
```diff
@@ -158,115 +161,266 @@ impl local::Exporter<OtapPdata> for OTAPExporter {
...
+        let (metrics_sender, metrics_receiver) = tokio::sync::mpsc::channel(64);
+        let (traces_sender, traces_receiver) = tokio::sync::mpsc::channel(64);
+        let (pdata_metrics_tx, mut pdata_metrics_rx) = tokio::sync::mpsc::channel(64);
+        let (shutdown_tx, shutdown_rx) = tokio::sync::watch::channel(false);
+        
+        let logs_handle = tokio::spawn(stream_arrow_batches(
```
Comment (lquerel) [inline rust/otap-dataflow/crates/otap/src/otap_exporter.rs:174]:
```suggestion
        // TODO check if we can expose/use spawn_local method in the effect handler 
        let logs_handle = tokio::spawn(stream_arrow_batches(
```

**Comment by lquerel** [comment]
**Please don't merge until I check this PR with our demo scenarios**

**Comment by lquerel** [comment]
Tested, all looks good.

File: rust/otap-dataflow/crates/otap/src/otap_exporter.rs [hunk 3]
```diff
@@ -158,115 +160,268 @@ impl local::Exporter<OtapPdata> for OTAPExporter {
...
+}
+
+#[allow(tail_expr_drop_order)]
+fn create_req_stream(
+    mut first_batch: OtapArrowRecords,
+    remaining_batches_rx: Arc<tokio::sync::Mutex<Receiver<OtapArrowRecords>>>,
+    signal_type: SignalType,
+    pdata_metrics_tx: Sender<PDataMetricsUpdate>,
+) -> impl IntoStreamingRequest<Message = BatchArrowRecords> {
+    stream! {
```
Comment (jmacd) [inline rust/otap-dataflow/crates/otap/src/otap_exporter.rs:366]: Looks good!

File: rust/otap-dataflow/crates/otap/src/otap_exporter.rs [hunk 4]
```diff
@@ -158,115 +160,268 @@ impl local::Exporter<OtapPdata> for OTAPExporter {
...
+) -> bool {
+    let mut shutdown = false;
+
+    // handle streaming responses until shutdown
+    while !shutdown {
+        tokio::select! {
+            res = res_stream.message() => {
+                match res {
+                    Ok(Some(_val)) => {
+                        _ = pdata_metrics_tx.send(PDataMetricsUpdate::IncExported(signal_type)).await;
```
Comment (jmacd) [inline rust/otap-dataflow/crates/otap/src/otap_exporter.rs:404]: Lost the TODO about Ack/Nack somewhere in here 😀

Comment (albertlockett) [reply rust/otap-dataflow/crates/otap/src/otap_exporter.rs:404]: oops :( my bad!
