### PR TITLE
[concurrentbatch] skip size==0 requests

### LINKED ISSUE #206: Concurrent batch processor: test flake / races
As seen in https://github.com/open-telemetry/otel-arrow/actions/runs/9310159268/job/25627016261 in #205.

In addition to that timeout, I checked and was easily able to reproduce a local race condition during CBP unittests. (Why is the race condition easy to repro but not generally causing CI/CD failures?)

### PR DESCRIPTION
**Pull request by jmacd**
Size=0 requests could get stuck in the concurrent batch processor if there are not other requests traveling through. This bug was able to cause test failures when race detection is enabled.

Fixes #206

### CODE REVIEW

**Review by lquerel — APPROVED** [review]

File: collector/processor/concurrentbatchprocessor/batch_processor.go [hunk 1]
```diff
@@ -471,11 +477,6 @@ func (b *shard) consumeAndWait(ctx context.Context, data any) error {
 	// The purpose of this function is to ensure semaphore
 	// releases all previously acquired bytes
 	defer func() {
-		if item.count == 0 {
```
Comment (moh-osman3) [inline collector/processor/concurrentbatchprocessor/batch_processor.go]: I think this check is needed in this deferred function otherwise we will hang waiting on `respCh` in the for loop on L484. i.e. we should only enter the goroutine on L483 if our context timed out and we have not received all responses. Otherwise we got all responses and decremented `item.count` (`item.count == 0`) and don't need to wait for anymore responses.

**Review by moh-osman3 — APPROVED** [review]

File: collector/processor/concurrentbatchprocessor/batch_processor.go (hunk 1 above)
Comment (jmacd) [reply collector/processor/concurrentbatchprocessor/batch_processor.go]: ah, of course! thank you
